// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @blind-peer/core
const encoding0 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.uint.preencode(state, m.length)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, m.length)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)

    return {
      key: r0,
      length: r1
    }
  }
}

// @blind-peer/cores
const encoding1 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.referrer) c.fixed32.preencode(state, m.referrer)
    if (m.priority) c.uint.preencode(state, m.priority)
    encoding1_3.preencode(state, m.cores)
  },
  encode(state, m) {
    const flags = (m.referrer ? 1 : 0) | (m.priority ? 2 : 0) | (m.announce ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.referrer) c.fixed32.encode(state, m.referrer)
    if (m.priority) c.uint.encode(state, m.priority)
    encoding1_3.encode(state, m.cores)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      referrer: (flags & 1) !== 0 ? c.fixed32.decode(state) : null,
      priority: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      announce: (flags & 4) !== 0,
      cores: encoding1_3.decode(state)
    }
  }
}

// @blind-peer/cores.cores, deferred due to recusive use
const encoding1_3 = c.array(c.frame(encoding1))

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@blind-peer/core':
      return encoding0
    case '@blind-peer/cores':
      return encoding1
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
